<?php
/**
 * Configuration settings for file upload system
 * Generated by setup.php on 2025-05-17 10:02:55
 */

// Maximum upload size in bytes (10GB)
$maxUploadSize = 10737418240; // 10GB in bytes

// Upload directory (absolute path)
$uploadDirectory = '/home/ubuntu/file_upload_system/uploads';

// Allowed file extensions (empty array means all types are allowed)
$allowedFileExtensions = [];

// Maximum execution time (seconds)
$maxExecutionTime = 3600; // 1 hour

// Maximum input time (seconds)
$maxInputTime = 3600; // 1 hour

// Post max size (should be slightly larger than upload max filesize)
$postMaxSize = 11811160064; // 11GB in bytes

// Memory limit
$memoryLimit = '1024M'; // 1GB

// You can modify these settings as needed
